const mongoose=require("mongoose")

const courseSchema=new mongoose.Schema(
    {
        courseName:{
            type:String,
            required:true,
            trim:true
        },
        courseDescription:{
            type:String,
        },
        instrurtor:{
            type:mongoose.Schema.Types.ObjectId,
            ref:"User",
            required:true
        },
        whatYouWillLearn:{
            type:String
        },
        courseContent:[
            {
                type:mongoose.Schema.Types.ObjectId,
                ref:"Section",
                required:true
            }
        ],
        ratingAndReviws:[
            {
                type:mongoose.Schema.Types.ObjectId,
                ref:"ratingAndReview"
            }
        ],
        price:{
            type:Number
        }, 
        thumbnail:{
            type:String
        },  
        tags:{
            type:mongoose.Schema.Types.ObjectId,
            ref:"Tag"
        },
        studentEnrolled:[
            {
                type:mongoose.Schema.Types.ObjectId,
                ref:"User",
                required:true
            }
        ]
    }
);

module.exports=mongoose.model("Course",courseSchema);