const mongoose=require("mongoose");

const userSchema=new mongoose.Schema({
    firstname:{
        type:String,
        required:true,
        trim:true,
    },
    lastname:{
        type:String,
        required:true,
        trim:true,
    },
    email:{
        type:String,
        required:true,
        trim:true
    },
    password:{
        type:String, 
        required:true,
    },
    contact:{
        type:String,
        required:true,
    },
    accountType:{
        type:String,
        enum:["Student","Admin","Instructor"],
        required:true
    },
    additionalDetails:{
        type:mongoose.Schema.type.ObjectId,
        ref:"Profile",
        required:true
    },
    courses:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:"Course"
        }
    ],
    image:{
        type:String,
        required:true
    },
    token:{
        type:String,
    },
    resentPasswordExpires:{
        type:Date,
    },
    courseProgress:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:"CourseProgress"        
        }
    ]
});

module.exports=mongoose.model("User",userSchema);